-- MySQL Script generated by MySQL Workbench
-- 01/30/17 19:46:04
-- Model: Payments Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema payments
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema payments
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `payments` DEFAULT CHARACTER SET utf8 ;
USE `payments` ;

-- -----------------------------------------------------
-- Table `payments`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payments`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payments`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payments`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `comment` VARCHAR(200) NULL,
  `roles_id` INT NOT NULL,
  PRIMARY KEY (`id`, `roles_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_users_roles1_idx` (`roles_id` ASC),
  CONSTRAINT `fk_users_roles1`
    FOREIGN KEY (`roles_id`)
    REFERENCES `payments`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payments`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payments`.`account` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` INT NOT NULL,
  `amount` INT NULL,
  `is_blocked` TINYINT(1) NULL,
  `comment` VARCHAR(200) NULL,
  `client_id` INT NOT NULL,
  PRIMARY KEY (`id`, `client_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `number_UNIQUE` (`number` ASC),
  INDEX `fk_account_client1_idx` (`client_id` ASC),
  CONSTRAINT `fk_account_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `payments`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payments`.`credit_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payments`.`credit_card` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` INT NOT NULL,
  `expiration_month` TINYINT NOT NULL,
  `expiration_year` TINYINT NOT NULL,
  `comment` VARCHAR(200) NULL,
  `account_id` INT NOT NULL,
  PRIMARY KEY (`id`, `account_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `number_UNIQUE` (`number` ASC),
  INDEX `fk_credit_card_account_idx` (`account_id` ASC),
  CONSTRAINT `fk_credit_card_account`
    FOREIGN KEY (`account_id`)
    REFERENCES `payments`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payments`.`cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payments`.`cities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payments`.`streets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payments`.`streets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `prefix` VARCHAR(10) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payments`.`address_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payments`.`address_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payments`.`addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payments`.`addresses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `zip` INT NULL,
  `building` INT NULL,
  `additional` VARCHAR(5) NULL,
  `apartment` INT NULL,
  `comment` VARCHAR(200) NULL,
  `city_id` INT NOT NULL,
  `street_id` INT NOT NULL,
  `client_id` INT NOT NULL,
  `address_type_id` INT NOT NULL,
  PRIMARY KEY (`id`, `client_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_address_city1_idx` (`city_id` ASC),
  INDEX `fk_address_street1_idx` (`street_id` ASC),
  INDEX `fk_address_client1_idx` (`client_id` ASC),
  INDEX `fk_address_address_type1_idx` (`address_type_id` ASC),
  CONSTRAINT `fk_address_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `payments`.`cities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_address_street1`
    FOREIGN KEY (`street_id`)
    REFERENCES `payments`.`streets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_address_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `payments`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_address_address_type1`
    FOREIGN KEY (`address_type_id`)
    REFERENCES `payments`.`address_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payments`.`phone_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payments`.`phone_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payments`.`phones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payments`.`phones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `country_code` TINYINT NOT NULL,
  `zone_code` TINYINT NOT NULL,
  `number` INT NOT NULL,
  `extension` INT NULL,
  `comment` VARCHAR(200) NULL,
  `phone_type_id` INT NOT NULL,
  `client_id` INT NOT NULL,
  PRIMARY KEY (`id`, `client_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_phone_phone_type1_idx` (`phone_type_id` ASC),
  INDEX `fk_phone_client1_idx` (`client_id` ASC),
  CONSTRAINT `fk_phone_phone_type1`
    FOREIGN KEY (`phone_type_id`)
    REFERENCES `payments`.`phone_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_phone_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `payments`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payments`.`email_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payments`.`email_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payments`.`emails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payments`.`emails` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(100) NOT NULL,
  `comment` VARCHAR(200) NULL,
  `email_type_id` INT NOT NULL,
  `client_id` INT NOT NULL,
  PRIMARY KEY (`id`, `client_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_email_email_type1_idx` (`email_type_id` ASC),
  INDEX `fk_email_client1_idx` (`client_id` ASC),
  UNIQUE INDEX `address_UNIQUE` (`address` ASC),
  CONSTRAINT `fk_email_email_type1`
    FOREIGN KEY (`email_type_id`)
    REFERENCES `payments`.`email_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_email_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `payments`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payments`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payments`.`payment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `amount` INT NULL,
  `destination` VARCHAR(100) NOT NULL,
  `comment` VARCHAR(200) NULL,
  `account_id` INT NOT NULL,
  `account_client_id` INT NOT NULL,
  PRIMARY KEY (`id`, `account_id`, `account_client_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_payment_account1_idx` (`account_id` ASC, `account_client_id` ASC),
  CONSTRAINT `fk_payment_account1`
    FOREIGN KEY (`account_id` , `account_client_id`)
    REFERENCES `payments`.`account` (`id` , `client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
